concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "zerotogitlab"
  url = "https://gitlab.yasserelkhayati.com"
  id = 3
  token = "glrt-t3_5LxBESXjkSomnY3Lxsog"
  token_obtained_at = 2025-03-22T21:40:43Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/etc/hosts:/etc/hosts"]
    shm_size = 0
    network_mtu = 0
