services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    environment:
      GITLAB_ROOT_EMAIL: "admin@yasserelkhayati.com"
      GITLAB_ROOT_PASSWORD: "SuperSecurePassword"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.yasserelkhayati.com'  # Modify this with your custom domain
        nginx['redirect_http_to_https'] = true
    ports:
      - '443:443'    # This ensures secure HTTPS access
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl:ro

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
