stages:
  - build
  - deploy

variables:
  CI_REGISTRY: "gitlab.yasserelkhayati.com:5050"
  CI_REGISTRY_IMAGE: "$CI_REGISTRY/root/zero-to-gitlab"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

build-image:
  stage: build
  tags: [docker]
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "done"

deploy-app:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags: [docker]
  script:
    - kubectl config use-context root/zero-to-gitlab:zerotogitlab
    - |
      kubectl create secret docker-registry gitlab-registry \
        --docker-server=$CI_REGISTRY \
        --docker-username=$CI_REGISTRY_USER \
        --docker-password=$CI_JOB_TOKEN \
        --namespace=default --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -f manifests/
    - kubectl rollout status deployment/hello-app
